# Generated by Django 3.1.7 on 2021-04-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0002_auto_20210410_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='100x60.gif', height_field='height_field', null=True, upload_to='MEDIA_SPECIALITY_IMAGE_DIR', width_field='width_field'),
        ),
    ]
