# Generated by Django 3.1.7 on 2021-04-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_auto_20210410_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(auto_now=True),
        ),
    ]
