# Generated by Django 3.1.7 on 2021-04-12 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_app', '0004_auto_20210411_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='100x60.gif', height_field='height_field', upload_to='MEDIA_COMPANY_IMAGE_DIR', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='100x60.gif', height_field='height_field', upload_to='MEDIA_SPECIALITY_IMAGE_DIR', width_field='width_field'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=8)),
                ('specialty', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('education', models.CharField(max_length=64)),
                ('experience', models.CharField(max_length=64)),
                ('portfolio', models.CharField(max_length=300)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
