# Generated by Django 3.1.7 on 2021-04-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_auto_20210412_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=64, verbose_name='Ваше образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(max_length=64, verbose_name='Ваш опыт'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(max_length=64, verbose_name='Ваш уровень'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.CharField(max_length=300, verbose_name='Ваше портфолио'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.PositiveIntegerField(max_length=8, verbose_name='Ваша желаемая зарплата'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.CharField(max_length=64, verbose_name='Ваша специальность'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(max_length=30, verbose_name='Ваш статус'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='surname',
            field=models.CharField(max_length=40, verbose_name='Ваша фамилия'),
        ),
    ]
