# Generated by Django 3.1.7 on 2021-04-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_auto_20210413_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.CharField(max_length=8, verbose_name='Ваша желаемая зарплата'),
        ),
    ]
